/*
 * Arm SCP/MCP Software
 * Copyright (c) 2021, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef FWK_MODULE_IDX_H
#define FWK_MODULE_IDX_H

#include <fwk_id.h>

#define FWK_MODULE_ID_RCAR4_SYSTEM_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_RCAR4_SYSTEM)
#define FWK_MODULE_ID_SCMI_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_SCMI)
#define FWK_MODULE_ID_TRANSPORT_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_TRANSPORT)
#define FWK_MODULE_ID_CLOCK_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_CLOCK)
#define FWK_MODULE_ID_RCAR4_CLOCK_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_RCAR4_CLOCK)
#define FWK_MODULE_ID_RCAR4_SYSTEM_POWER_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_RCAR4_SYSTEM_POWER)
#define FWK_MODULE_ID_RCAR4_MFISMH_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_RCAR4_MFISMH)
#define FWK_MODULE_ID_POWER_DOMAIN_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_POWER_DOMAIN)
#define FWK_MODULE_ID_RCAR4_PD_SYSC_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_RCAR4_PD_SYSC)
#define FWK_MODULE_ID_RCAR4_PD_CORE_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_RCAR4_PD_CORE)
#define FWK_MODULE_ID_SDS_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_SDS)
#define FWK_MODULE_ID_RESET_DOMAIN_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_RESET_DOMAIN)
#define FWK_MODULE_ID_RCAR4_RESET_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_RCAR4_RESET)
#define FWK_MODULE_ID_SCMI_RESET_DOMAIN_INIT FWK_ID_MODULE_INIT(FWK_MODULE_IDX_SCMI_RESET_DOMAIN)


#define FWK_MODULE_ID_RCAR4_SYSTEM FWK_ID_MODULE(FWK_MODULE_IDX_RCAR4_SYSTEM)
#define FWK_MODULE_ID_SCMI FWK_ID_MODULE(FWK_MODULE_IDX_SCMI)
#define FWK_MODULE_ID_TRANSPORT FWK_ID_MODULE(FWK_MODULE_IDX_TRANSPORT)
#define FWK_MODULE_ID_CLOCK FWK_ID_MODULE(FWK_MODULE_IDX_CLOCK)
#define FWK_MODULE_ID_RCAR4_CLOCK FWK_ID_MODULE(FWK_MODULE_IDX_RCAR4_CLOCK)
#define FWK_MODULE_ID_RCAR4_SYSTEM_POWER FWK_ID_MODULE(FWK_MODULE_IDX_RCAR4_SYSTEM_POWER)
#define FWK_MODULE_ID_RCAR4_MFISMH FWK_ID_MODULE(FWK_MODULE_IDX_RCAR4_MFISMH)
#define FWK_MODULE_ID_POWER_DOMAIN FWK_ID_MODULE(FWK_MODULE_IDX_POWER_DOMAIN)
#define FWK_MODULE_ID_RCAR4_PD_SYSC FWK_ID_MODULE(FWK_MODULE_IDX_RCAR4_PD_SYSC)
#define FWK_MODULE_ID_RCAR4_PD_CORE FWK_ID_MODULE(FWK_MODULE_IDX_RCAR4_PD_CORE)
#define FWK_MODULE_ID_SDS FWK_ID_MODULE(FWK_MODULE_IDX_SDS)
#define FWK_MODULE_ID_RESET_DOMAIN FWK_ID_MODULE(FWK_MODULE_IDX_RESET_DOMAIN)
#define FWK_MODULE_ID_RCAR4_RESET FWK_ID_MODULE(FWK_MODULE_IDX_RCAR4_RESET)
#define FWK_MODULE_ID_SCMI_RESET_DOMAIN FWK_ID_MODULE(FWK_MODULE_IDX_SCMI_RESET_DOMAIN)


enum fwk_module_idx {
    FWK_MODULE_IDX_RCAR4_SYSTEM = 0,
    FWK_MODULE_IDX_SCMI = 1,
    FWK_MODULE_IDX_TRANSPORT = 2,
    FWK_MODULE_IDX_CLOCK = 3,
    FWK_MODULE_IDX_RCAR4_CLOCK = 4,
    FWK_MODULE_IDX_RCAR4_SYSTEM_POWER = 5,
    FWK_MODULE_IDX_RCAR4_MFISMH = 6,
    FWK_MODULE_IDX_POWER_DOMAIN = 7,
    FWK_MODULE_IDX_RCAR4_PD_SYSC = 8,
    FWK_MODULE_IDX_RCAR4_PD_CORE = 9,
    FWK_MODULE_IDX_SDS = 10,
    FWK_MODULE_IDX_RESET_DOMAIN = 11,
    FWK_MODULE_IDX_RCAR4_RESET = 12,
    FWK_MODULE_IDX_SCMI_RESET_DOMAIN = 13,
    FWK_MODULE_IDX_COUNT = 14,

};

static const fwk_id_t fwk_module_id_rcar4_system = FWK_MODULE_ID_RCAR4_SYSTEM_INIT;
static const fwk_id_t fwk_module_id_scmi = FWK_MODULE_ID_SCMI_INIT;
static const fwk_id_t fwk_module_id_transport = FWK_MODULE_ID_TRANSPORT_INIT;
static const fwk_id_t fwk_module_id_clock = FWK_MODULE_ID_CLOCK_INIT;
static const fwk_id_t fwk_module_id_rcar4_clock = FWK_MODULE_ID_RCAR4_CLOCK_INIT;
static const fwk_id_t fwk_module_id_rcar4_system_power = FWK_MODULE_ID_RCAR4_SYSTEM_POWER_INIT;
static const fwk_id_t fwk_module_id_rcar4_mfismh = FWK_MODULE_ID_RCAR4_MFISMH_INIT;
static const fwk_id_t fwk_module_id_power_domain = FWK_MODULE_ID_POWER_DOMAIN_INIT;
static const fwk_id_t fwk_module_id_rcar4_pd_sysc = FWK_MODULE_ID_RCAR4_PD_SYSC_INIT;
static const fwk_id_t fwk_module_id_rcar4_pd_core = FWK_MODULE_ID_RCAR4_PD_CORE_INIT;
static const fwk_id_t fwk_module_id_sds = FWK_MODULE_ID_SDS_INIT;
static const fwk_id_t fwk_module_id_reset_domain = FWK_MODULE_ID_RESET_DOMAIN_INIT;
static const fwk_id_t fwk_module_id_rcar4_reset = FWK_MODULE_ID_RCAR4_RESET_INIT;
static const fwk_id_t fwk_module_id_scmi_reset_domain = FWK_MODULE_ID_SCMI_RESET_DOMAIN_INIT;


#endif /* FWK_MODULE_IDX_H */
