#
# LICENSE
#

set(SCP_FIRMWARE "rcar4-bl")

set(SCP_FIRMWARE_TARGET "rcar4-bl")

set(SCP_TOOLCHAIN_INIT "GNU")

set(SCP_GENERATE_FLAT_BINARY_INIT TRUE)

set(SCP_ENABLE_NOTIFICATIONS_INIT TRUE)

set(SCP_ENABLE_SCMI_RESET_INIT TRUE)

set(SCP_ENABLE_IPO_INIT FALSE)

set(SCP_ENABLE_OUTBAND_MSG_SUPPORT_INIT TRUE)

set(SCP_ARCHITECTURE "armv8-a") # muss ich noch implementieren (armv8-r) // vllt mal testen mit armv8-a arch

list(PREPEND SCP_MODULE_PATHS "${CMAKE_CURRENT_LIST_DIR}/../module/rcar4_reset")

list(APPEND SCP_MODULES "rcar4-reset")